### ISSUE TITLE
Random page reload because of connection losses in Firefox

### ISSUE THREAD

**Issue by bastetfurry** [OmarShehata/jpeg-sandbox#1]
I get random page reloads because according to the console log some server connection to wss://jpeg-sandbox.glitch.me:3000/ couldn't be established.

Browser: Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0

**Comment by OmarShehata** [comment]
Thanks for reporting @bastetfurry ! I'm pretty sure this is because of using Vite on Glitch, which tries to have hotreload working. It makes more sense to have this working locally.

Not sure if there's a recommended way to deploy a Vite app on Glitch, or I could just build a static version and put that on glitch/github pages.

**Comment by OvermindDL1** [comment]
Same thing here, can't use the page as it keeps reloading every 30 seconds.  Static compiled-together version might be best?  Minimal download size and fastest loading then.

**Comment by OmarShehata** [comment]
> Static compiled-together version might be best? Minimal download size and fastest loading then.

That's true, I was hoping to keep it this way so that if someone wanted to tweak it on-the-fly in the browser they'd be able to do that by remixing/editing on Glitch (via this link https://glitch.com/edit/#!/jpeg-sandbox).

I just made a change that adds a `vite.config.js` on Glitch, that I _think_ fixes it. Could you let me know if it's still happening for you @OvermindDL1 @bastetfurry ?

I also added a link to the Gitch edit URL in the README.

**Comment by OvermindDL1** [comment]
I played with it for a couple minutes and no reloading, so it looks good here?  :-)

Really love how visual these changes are!  I've tried to describe it to others but this is just amazingly visual!

**Comment by OmarShehata** [comment]
Thanks for confirming, and thank you so much for the kind words 😊
